ConsultaMedicos/ConsultaMedicos/Controllers/MedicosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ConsultaMedicos.Models;

namespace ConsultaMedicos.Controllers
{
    public class MedicosController : BaseController
    {
        private CadeMeuMedicoBDEntities db = new CadeMeuMedicoBDEntities();

        // GET: Medicos
        public ActionResult Index()
        {
            var medicos = db.Medicos.ToList();
            //vai retornar uma lista do banco da tabela médicos
            
            return View(medicos);
        }

        public ActionResult Adicionar()
        {
            //cria os itens de seleção buscando os itens em cada tabela (tabela, valor do item e texto que aparecerá)
            ViewBag.IdCidade = new SelectList(db.Cidades, "IDCidade", "Nome");
            ViewBag.IdEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Medicos medico)
        {
            if (ModelState.IsValid)
            {
                db.Medicos.Add(medico);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade","Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades,"IDEspecialidade","Nome", medico.IDEspecialidade);
            return View(medico);
        }

        public ActionResult Editar(long id)
        {
            Medicos medico = db.Medicos.Find(id);
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade","Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades,"IDEspecialidade", "Nome", medico.IDEspecialidade);
            return View(medico);
        }

        [HttpPost]
        public ActionResult Editar(Medicos medico)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medico).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome", medico.IDEspecialidade);
            return View(medico);
        }

        public string Excluir(long id)
        {
            try
            {
                Medicos medico = db.Medicos.Find(id);
                db.Medicos.Remove(medico);
                db.SaveChanges();
                return Boolean.TrueString;
            }
            catch
            {
                return Boolean.FalseString;
            }
        }
    }
}

ConsultaMedicos/ConsultaMedicos/Views/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Consulte o médico - @ViewBag.Title </title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    
</head>

<body>

    <div class="navbar navbar-inverse navbar-fixed-top bg-dark">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Consulte o médico</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li id="menuMedicos">
                        @Html.ActionLink("Médicos", "Index", "Medicos")
                    </li>
                    <li id="menuMedicos">
                        @Html.ActionLink("Cidades", "Index", "Cidades")
                    </li>
                    <li id="menuMedicos">
                        @Html.ActionLink("Especialidades", "Index", "Especialidades")
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        @RenderBody()
    </div>

    <script src="@Url.Content("~/Scripts/jquery-3.4.1.min.js")">
    </script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")">
    </script>

    @RenderSection("script", required: false)




    @*
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    *@

</body>
</html>